# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSToolBox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSToolBox
pod 'SwiftyUserDefaults'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'Whisper'
pod 'Hue'
pod 'IQKeyboardManagerSwift'
pod 'DateToolsSwift'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'SwiftyUserDefaults'
pod 'Localize-Swift'
pod 'M13ProgressSuite'
end
